---
engines:
  eslint:
    enabled: true
    checks:
      fatal:
        enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - javascript
    checks:
      Similar code:
        enabled: false
  fixme:
    enabled: true
    checks:
      XXX:
        enabled: false
ratings:
  paths:
  - "**.js"
exclude_paths:
- "**.test.js"
